# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{inkling}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = %q{2010-09-06}
  s.default_executable = %q{inkling}
  s.description = %q{A content framework engine for Rails 3}
  s.executables = ["inkling"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "app/controllers/inkling/admin/base_controller.rb",
     "app/controllers/inkling/admin/content_types_controller.rb",
     "app/controllers/inkling/admin/roles_controller.rb",
     "app/controllers/inkling/admin/users_controller.rb",
     "app/controllers/inkling/base_controller.rb",
     "app/controllers/inkling/home_controller.rb",
     "app/controllers/inkling/paths_controller.rb",
     "app/controllers/inkling/proxying_controller.rb",
     "app/controllers/inkling/users/confirmations_controller.rb",
     "app/controllers/inkling/users/passwords_controller.rb",
     "app/controllers/inkling/users/sessions_controller.rb",
     "app/models/inkling/path.rb",
     "app/models/inkling/permission.rb",
     "app/models/inkling/role.rb",
     "app/models/inkling/role_membership.rb",
     "app/models/inkling/user.rb",
     "app/views/inkling/admin/content_types/index.html.erb",
     "app/views/inkling/admin/roles/index.html.erb",
     "app/views/inkling/admin/sites/index.html.erb",
     "app/views/inkling/admin/users/_form.html.erb",
     "app/views/inkling/admin/users/edit.html.erb",
     "app/views/inkling/admin/users/index.html.erb",
     "app/views/inkling/admin/users/new.html.erb",
     "app/views/inkling/admin/users/show.html.erb",
     "app/views/inkling/home/_dashboard.html.erb",
     "app/views/inkling/home/dashboard.html.erb",
     "app/views/inkling/paths/_content_form.html.erb",
     "app/views/inkling/paths/_path.html.erb",
     "app/views/inkling/paths/index.html.erb",
     "app/views/inkling/users/confirmations/new.html.erb",
     "app/views/inkling/users/mailer/confirmation_instructions.html.erb",
     "app/views/inkling/users/mailer/reset_password_instructions.html.erb",
     "app/views/inkling/users/mailer/unlock_instructions.html.erb",
     "app/views/inkling/users/passwords/edit.html.erb",
     "app/views/inkling/users/passwords/new.html.erb",
     "app/views/inkling/users/registrations/edit.html.erb",
     "app/views/inkling/users/registrations/new.html.erb",
     "app/views/inkling/users/sessions/new.html.erb",
     "app/views/inkling/users/shared/_links.erb",
     "app/views/inkling/users/unlocks/new.html.erb",
     "app/views/layouts/inkling/manage.html.erb",
     "config/initializers/acts_as_content_init.rb",
     "config/initializers/rspec_generator.rb",
     "config/routes.rb",
     "lib/better_nested_set.rb",
     "lib/better_nested_set_helper.rb",
     "lib/generators/inkling_generator.rb",
     "lib/generators/templates/create_inkling_tables.rb",
     "lib/inkling.rb",
     "lib/inkling/ability.rb",
     "lib/inkling/commands.rb",
     "lib/inkling/commands/generator.rb",
     "lib/inkling/content.rb",
     "lib/inkling/engine.rb",
     "lib/inkling/routing.rb",
     "lib/inkling/util/migration_helpers.rb",
     "lib/inkling/version.rb",
     "lib/tasks/cucumber.rake",
     "lib/tasks/inkling.rake",
     "lib/tasks/rspec.rake"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A content framework engine for Rails 3}
  s.test_files = [
    "spec/controllers/admin/folder_entries_spec.rb",
     "spec/controllers/admin/folders_spec.rb",
     "spec/controllers/admin/proxy_admin_spec.rb",
     "spec/controllers/proxy_show_spec.rb",
     "spec/models/path_spec.rb",
     "spec/models/permission_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/inkling_spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<devise>, [">= 0"])
      s.add_runtime_dependency(%q<inherited_resources>, [">= 0"])
      s.add_runtime_dependency(%q<formtastic>, [">= 0"])
      s.add_runtime_dependency(%q<cancan>, [">= 0"])
    else
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<inherited_resources>, [">= 0"])
      s.add_dependency(%q<formtastic>, [">= 0"])
      s.add_dependency(%q<cancan>, [">= 0"])
    end
  else
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<inherited_resources>, [">= 0"])
    s.add_dependency(%q<formtastic>, [">= 0"])
    s.add_dependency(%q<cancan>, [">= 0"])
  end
end

