# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{inkling}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.date = %q{2010-05-18}
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "app/controllers/admin/inkling/base_controller.rb",
     "app/controllers/admin/inkling/proxy_admin_controller.rb",
     "app/controllers/admin/inkling/folders_controller.rb",
     "app/controllers/admin/inkling/foos_controller.rb",
     "app/models/inkling/folder.rb",
     "app/models/inkling/folder_entry.rb",
     "app/models/inkling/foo.rb",
     "app/models/inkling/role.rb",
     "app/models/inkling/type.rb",
     "app/models/inkling/user.rb",
     "app/views/admin/inkling/folders/_form.html.erb",
     "app/views/admin/inkling/folders/_secondary_menu.html.erb",
     "app/views/admin/inkling/folders/edit.html.erb",
     "app/views/admin/inkling/folders/index.html.erb",
     "app/views/admin/inkling/folders/new.html.erb",
     "app/views/admin/inkling/foos/_form.html.erb",
     "app/views/admin/inkling/foos/_secondary_menu.html.erb",
     "app/views/admin/inkling/foos/edit.html.erb",
     "app/views/admin/inkling/foos/index.html.erb",
     "app/views/admin/inkling/foos/new.html.erb",
     "app/views/layouts/administration.html.erb",
     "config/initializers/acts_as_content_init.rb",
     "config/initializers/content_loading.rb",
     "config/initializers/rspec_generator.rb",
     "config/routes.rb",
     "lib/better_nested_set.rb",
     "lib/better_nested_set_helper.rb",
     "lib/generators/inkling/inkling_generator.rb",
     "lib/generators/inkling/templates/create_inkling_folders.rb",
     "lib/generators/inkling/templates/create_inkling_users.rb",
     "lib/inkling.rb",
     "lib/inkling/content.rb",
     "lib/inkling/engine.rb",
     "lib/mob.rb",
     "lib/tasks/cucumber.rake",
     "lib/tasks/rspec.rake"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A content framework engine for Rails 3}
  s.test_files = [
    "spec/controllers/admin/proxy_admin_spec.rb",
     "spec/controllers/admin/folders_spec.rb",
     "spec/models/folder_entry_spec.rb",
     "spec/models/folder_spec.rb",
     "spec/models/foo_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/inkling_spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

