source 'http://rubygems.org'

gem 'rails', '3.0.0.rc'

#choose a db adaptor.
gem "pg"
#gem 'sqlite3-ruby', :require => 'sqlite3'

gem "ruby-debug", :group => [:test, :development]

gem 'inkling', :path => '../'


gem "rspec-rails", ">= 2.0.0.beta.8", :group => [:test, :development]
gem 'capybara'
gem 'cucumber-rails'
gem 'cucumber', '>= 0.7.2'
gem 'spork'
gem 'launchy'    # So you can do Then show me the page


# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri', '1.4.1'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for certain environments:
# gem 'rspec', :group => :test
# group :test do
#   gem 'webrat'
# end
